version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      check-type-assertions: false

formatters:
  enable:
    - gofmt

output:
  sort-order:
    - file
