import type { GlobalThemeOverrides } from 'naive-ui'

export const domusThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#4f5fe7',
    primaryColorHover: '#6271ed',
    primaryColorPressed: '#3e4dcc',
    primaryColorSuppl: '#6271ed',
    infoColor: '#4f5fe7',
    infoColorHover: '#6271ed',
    infoColorPressed: '#3e4dcc',
    successColor: '#238468',
    warningColor: '#ad741f',
    errorColor: '#c2414f',
    bodyColor: '#f4f6fa',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    avatarColor: '#4f5fe7',
    textColorBase: '#172033',
    borderColor: '#dfe4ee',
    borderRadius: '12px',
    textColor2: '#30394d',
    textColor3: '#626d82',
    placeholderColor: '#657087',
    iconColor: '#626d82',
    fontSize: '14px',
    fontSizeSmall: '13px',
    fontSizeMini: '12px',
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  Button: {
    heightTiny: '28px',
    heightSmall: '36px',
    heightMedium: '42px',
    heightLarge: '48px',
    borderRadiusTiny: '8px',
    borderRadiusSmall: '10px',
    borderRadiusMedium: '11px',
    borderRadiusLarge: '12px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontWeight: '650',
    paddingSmall: '0 14px',
    paddingMedium: '0 18px',
  },
  Card: {
    borderRadius: '18px',
    paddingMedium: '24px',
    boxShadow: '0 18px 55px rgba(26, 36, 58, 0.09)',
  },
  Dialog: {
    borderRadius: '18px',
  },
  Dropdown: {
    optionHeightMedium: '36px',
    borderRadius: '12px',
    fontSizeMedium: '13px',
  },
  Input: {
    heightSmall: '36px',
    heightMedium: '42px',
    heightLarge: '48px',
    borderRadius: '11px',
    placeholderColor: '#657087',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    paddingMedium: '0 14px',
  },
  InternalSelection: {
    heightTiny: '28px',
    heightSmall: '36px',
    heightMedium: '42px',
    heightLarge: '48px',
    borderRadius: '11px',
    placeholderColor: '#657087',
  },
  Menu: {
    itemHeight: '44px',
    fontSize: '14px',
    itemColorHover: '#f0f2f8',
    itemColorActive: '#e9edff',
    itemColorActiveHover: '#e5e9ff',
    itemTextColorActive: '#4353d5',
    itemIconColorActive: '#4f5fe7',
  },
  Popover: {
    borderRadius: '16px',
    padding: '14px',
    boxShadow: '0 20px 60px rgba(22, 31, 52, 0.16), 0 2px 10px rgba(22, 31, 52, 0.06)',
  },
  DataTable: {
    borderRadius: '14px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    thColor: '#f7f8fb',
    thTextColor: '#657087',
    thFontWeight: '650',
    thPaddingSmall: '13px 16px',
    tdPaddingSmall: '15px 16px',
    borderColor: '#e9ecf2',
    tdColorHover: '#f8f9fc',
  },
  Tabs: {
    tabFontWeight: '550',
    tabFontWeightActive: '700',
  },
}

const darkCommon: NonNullable<GlobalThemeOverrides['common']> = {
  primaryColor: '#6d7df2',
  primaryColorHover: '#8290f6',
  primaryColorPressed: '#5a6ae0',
  primaryColorSuppl: '#8290f6',
  infoColor: '#6d7df2',
  infoColorHover: '#8290f6',
  infoColorPressed: '#5a6ae0',
  successColor: '#4fb08d',
  warningColor: '#c99a4a',
  errorColor: '#e06a78',
  bodyColor: '#12151d',
  cardColor: '#1a1f2b',
  modalColor: '#1a1f2b',
  popoverColor: '#1a1f2b',
  avatarColor: '#6d7df2',
  textColorBase: '#e7ebf3',
  borderColor: '#2b3243',
  textColor2: '#cdd4e0',
  textColor3: '#9aa4b8',
  placeholderColor: '#7d8798',
  iconColor: '#9aa4b8',
}

export const domusDarkThemeOverrides: GlobalThemeOverrides = {
  ...domusThemeOverrides,
  common: { ...domusThemeOverrides.common, ...darkCommon },
  Input: { ...domusThemeOverrides.Input, placeholderColor: '#7d8798' },
  InternalSelection: { ...domusThemeOverrides.InternalSelection, placeholderColor: '#7d8798' },
  Menu: {
    ...domusThemeOverrides.Menu,
    itemColorHover: '#232936',
    itemColorActive: '#28304f',
    itemColorActiveHover: '#2c3558',
    itemTextColorActive: '#a9b6ff',
    itemIconColorActive: '#8b9bff',
  },
  DataTable: {
    ...domusThemeOverrides.DataTable,
    thColor: '#1e242f',
    thTextColor: '#9aa4b8',
    borderColor: '#2b3243',
    tdColorHover: '#222836',
  },
  Popover: {
    ...domusThemeOverrides.Popover,
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.5), 0 2px 10px rgba(0, 0, 0, 0.35)',
  },
}
